### ISSUE TITLE
BP Form - Class "JEventDispatcher" not found...

### ISSUE THREAD

**Issue by florentdewas** [bpextensions/mod_bpform#21]
Hello,

migration from j3.9 to j4
php 8.2.18
url: https://orgamed-services.com/nous-contacter.html

"BP Form" first install.
without captcha, everything is fine
but activating captcha on BP Form module returns an error : Class "JEventDispatcher" not found

do i miss something?

thanks

**Comment by artur-stepien** [comment]
Hi. You are using a Joomla! 3 module version in Joomla! 4. Module for Joomla! 4 is almost ready (there are 2 issues we need to fix before releasing) but not sure about release date. Most likely end of month. New module have more features and is mostly incompatible with previous one so you would need to create the form again.

**Comment by florentdewas** [comment]
don't i feel stupid ?  :( yes i do !!!!
